---
# tasks file for role_win_mssqlserver

- name: Create a dba group
  ansible.windows.win_group:
    name: "{{ dba_local_group }}"
    description: Local DBA Group
    state: present

- name: Ensure db users are present
  ansible.windows.win_user:
    name: "{{ item }}"
    password: "{{ db_pw }}"
    state: present
    groups: 
      - Administrators
      - "{{ dba_local_group }}"
  loop: "{{ db_admins }}"

#- name: Add domain users to local Admin group - skip
#  win_group_membership:
#    name: Administrators
#    members: '{{ db_admins }}'
#    state: present

- name: Add the SQL engine account to Lock pages in memory
  ansible.windows.win_user_right:
    name: SeLockMemoryPrivilege
    users:
    - '{{ db_engine_user }}'
    action: add

- name: Add the SQL engine account to Perform volume maintenance task
  ansible.windows.win_user_right:
    name: SeManageVolumePrivilege
    users:
    - '{{ db_engine_user }}'
    action: add
  
- name: Configure Local DTC - Distributed Transaction Coordinator
  ansible.windows.win_shell: Set-DtcNetworkSetting -DtcName "Local" -AuthenticationLevel "NoAuth" -InboundTransactionsEnabled $true -OutboundTransactionsEnabled $true -RemoteAdministrationAccessEnabled $true -RemoteClientAccessEnabled $true -XATransactionsEnabled $true -Confirm:$false

- name: Create SQL directories
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop: '{{ db_dirs }}'

- name: Change power play to High Performance
  ansible.windows.win_shell: powercfg.exe /setactive 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c

- name: Download MS SQL server install file
  ansible.windows.win_get_url:
    url: '{{ inst_url }}'
    dest: '{{ inst_file }}'

- name: Create SQLServer.ini file for silent install
  ansible.windows.win_template:
    src: '{{ inst_db_type }}.ini.j2'
    dest: '{{ inst_config_file }}'

- name: Temporarily disable UAC - User Account Control
  ansible.windows.win_shell: 'REG ADD "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 0 /f'

- name: Run SQL Server Installer command-line
  ansible.windows.win_command: "{{ inst_file }} /Q /CONFIGURATIONFILE={{ inst_config_file }} /IACCEPTSQLSERVERLICENSETERMS=True /HP"
  become_user: domain/user - skip

#- name: Create sql script file to create DBATools DB
#  win_template:
#    src: 'DBCreate.sql.j2'
#    dest: '{{ inst_dbcreate_file }}'

#- name: Create DBTools DB
#  win_command: "sqlcmd -U sa -P {{ db_sapwd }} -i {{ inst_dbcreate_file }}"

- name: Re-enable UAC
  ansible.windows.win_shell: 'REG ADD "HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System" /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 5 /f'

- name: Clean-up by removing config file and install file
  ansible.windows.win_file:
    path: "{{ item }}"
    state: absent
  loop:
    - '{{ inst_config_file }}'
    - '{{ inst_file }}'
#    - '{{ inst_dbcreate_file }}'

- name: Reboot windows
  ansible.windows.win_reboot: